name: Python Code Standards Check

on:
  pull_request:
    branches:
      - main  # You can specify the branch name as per your requirement

jobs:
  code-quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you're using
    
    - name: Install Dependencies
      run: pip install black flake8 isort
      
    - name: Check Code with Black
      run: black --check .
      
    - name: Check Code with Flake8
      run: flake8 --ignore=E501 .
      
    - name: Check Imports with isort
      run: isort --check-only --diff .
